[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "project_git_cheak"
version = "0.1.0"
description = "Sample CI/CD Python project"
authors = [
    { name = "Neelachala Nayak" }
]
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "flask"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]